[build]
  command = "echo 'Static site - no build needed'"
  publish = "/"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  GITHUB_CLIENT_ID = "Ov23liMg9JVVvdzmNuxl"
  REDIRECT_URI = "https://exe-joemae.github.io/Xx_TEKITOU-NAME_xX/admin/"

[[functions]]
  node_bundler = "esbuild"
  directory = "api"
